### PR TITLE
fix that pyramidvue was referred to as pyramidVue

### PR DESCRIPTION
**Pull request by tdamsma**

### CODE REVIEW

**Comment by eddyekofo94** [comment]
@tdamsma Sorry, I am extremely busy so I didn't get to it (although it was a quick fix). All help is welcomed.

**Comment by tdamsma** [comment]
I'm just trying to see if I can hack in hot module replacement. If I succeed, I'll let you know

**Comment by eddyekofo94** [comment]
I tried also but I had a deadline so I had to put that aside. But if you wish to collab let me know.

**Comment by tdamsma** [comment]
A little bit of collaboration is always nice!

**Pull request merged**
